### ISSUE TITLE
Crash at world load

### ISSUE THREAD

**Issue by vivagabe** [OreCruncher/DynamicSurroundingsFabric#101]
Using forge 1.20.1 with sinytra connector. hopefully an easy fix.

[crash-2024-03-24_20.25.39-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14738436/crash-2024-03-24_20.25.39-client.txt)

**Comment by OreCruncher** [comment]
Dupe of #98 ?

**Comment by OreCruncher** [comment]
Closing as duplicate.
