### ISSUE TITLE
[1.20.1] Bug: Logs being spammed

### ISSUE THREAD

**Issue by Arbee4ever** [OreCruncher/DynamicSurroundingsFabric#102]
Whenever I launch my game and have the "Music" Volume slider set to 0%, this mod keeps spamming `[19:28:48] [Render thread/INFO]: Play Music: minecraft:music.menu{newSystem false, range 16.000000}` into my logs. When I then go into the options and set it to 100% exit the options and set it back to 0%, it doesn't spam anymore, but when I now enter a game it spams the same line only with `music.game` instead of `music.menu`. I think this is caused by this line: https://github.com/OreCruncher/DynamicSurroundingsFabric/blob/d9279ec935d62c5c26731012619394fe056cbc5a/src/main/java/org/orecruncher/dsurround/mixins/audio/MixinMusicManager.java#L69

**Comment by Arbee4ever** [comment]
Also, I'm on version 0.3.3 of this mod

**Comment by Arbee4ever** [comment]
(Also would be nice if you changed your logging to **always** include your modid, as I didn't have anything to go off of in finding what mod did this in my modpack)

**Comment by Arbee4ever** [comment]
OK, so apparently it only does this in the modpack I'm playing, so it must be another mod causing this mod to malfunction. (I'm playing this modpack if you want to try and find the mod combination casuing this: https://modrinth.com/modpack/layncesblueprint (on version 1.1.1))

**Comment by OreCruncher** [comment]
Not sure how frequent the spamming is.  This debug trace is emitted whenever the MusicManager attempts to play situational music. Based on the pack description in on Modrinth I suspect Infinite Music.  Looking at that mod's code is removes the delay between situational music plays.  With a 0% music volume this means it could trigger play every tick.  Talk about sound exhaustion. :)  My plan is to change my log statement into debug trace.

**Comment by Arbee4ever** [comment]
After disabling the Infinite Music mod, the spamming stopped. And yes, it was something along the lines of once every tick.

**Comment by ACE1337x** [comment]
im running into this issue as well but when fighting the Ender Dragon with the Ender Dragon Fight Remastered mod, and the phase 2 music doesn't play while this mod is installed

**Comment by OreCruncher** [comment]
Fixed in 1.21.1-0.4.0
