### ISSUE TITLE
Missing ambient sounds for `flower_forest` biome (0.3.3)

### ISSUE THREAD

**Issue by augustsaintfreytag** [OreCruncher/DynamicSurroundingsFabric#106]
Minecraft Version: 1.20.1
Fabric API Version: 0.92.0
DS Version: 0.3.3

When walking into a flower forest biome (a vanilla biome), the air is dead silent. Moving towards the edges of the biome, I can start to hear the adjacent biome's ambience but once I move back in, it gets silent again. I've checked the files and the only strange thing to be is that its only mention is called `flower_forests.json` but the biome is usually not suffixed with an extra "s".

I've tried to create a resource pack that adds in a file `flower_forest.json` right next to it but that did not seem to bring back the sounds. I don't know if biomes must be referenced in other parts of the mod, too, to make this work.

**Comment by OreCruncher** [comment]
Fixed in 1.21.1-0.4.0
