### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by vico93** [OreCruncher/DynamicSurroundingsFabric#116]
I'm not opening this as a "please do this urgently" type of thing (even because 1.21 will be dropped officially only Thursday), instead just as a way to mark it's not compatible yet.

**Comment by JotaRata** [comment]
Any updates on this?

**Comment by MotMomet** [comment]
Any updates on this?

**Comment by OreCruncher** [comment]
Working on 1.21.1 for Fabric and NeoForge.

**Comment by MotMomet** [comment]
> Working on 1.21.1 for Fabric and NeoForge.

THANK YOU! THE GOAT IS BACK!!!!!

**Comment by Jaxinz** [comment]
> Working on 1.21.1 for Fabric and NeoForge.

please 1.21.4 too

**Comment by OreCruncher** [comment]
Fixed in 1.21.1-0.4.0.  I am trying to find out the relative popularity of 1.21.4 to see if my time investment would pay off. ;)
