### ISSUE TITLE
Armor sounds missing/removed?

### ISSUE THREAD

**Issue by PapaDimitri** [OreCruncher/DynamicSurroundingsFabric#121]
I ve noticed when going from 1.19.2 to 1.20.1 that those cool armor noise is gone? I checked the jar mod itself and many sounds are gone. Btw I m using forge so i m using connector mod idk maybe thats the reason

**Comment by OreCruncher** [comment]
The armor sound feature of 1.19.2 was tied to footsteps. For 1.20.x+ I removed the footstep feature. I did carry some of those features forward:

* Walk through brush
* There are armor sounds but not as pronounced as 1.19.2
* No step sounds for mobs

Depending on your platform you can use Presence Footsteps to get a lot of those effects.
