### ISSUE TITLE
ConcurrentModificationException due to ThreadLocalRandom Accessed from Different Thread

### ISSUE THREAD

**Issue by poqdavid** [OreCruncher/DynamicSurroundingsFabric#122]
I realize this issue has been previously reported, but it's causing numerous exceptions in the log.
Here is the exception log: https://mclo.gs/ODKBUke

Fabric 1.20.1
C2ME 0.2.0+alpha.11.8
DynamicSurroundings 0.3.3

**Comment by OreCruncher** [comment]
Fixed in 1.21.1-0.4.0
