### ISSUE TITLE
Discord link modrinth not working

### ISSUE THREAD

**Issue by MrCode200** [OreCruncher/DynamicSurroundingsFabric#125]
Hi :), i found your amazing mod and wanted to ask some questions in the discord but the link didnt work.
(No need to answer the question here though nice if you could)

Does this mod also disable its cave sound features if sound physics is installed. Or does it get overwritten ... (Sry am no mod developer so dont know how the hicharchy of mods work)

Thanks for your amazing mod :)

**Comment by MrCode200** [comment]
Also if the ambiance sounds work with Ambient surroundings mod or not

**Comment by OreCruncher** [comment]
Dynamic Surroundings should run along side of Ambient Sounds.  As for the discord link I removed from Modrinth for now.
