### ISSUE TITLE
FIx the sounds.json

### ISSUE THREAD

**Issue by Gotlicked** [OreCruncher/DynamicSurroundingsFabric#128]
Multiple events in the sounds.json have broken paths that have to either be corrected, or removed due to non-existing sound files:

Log events:

226 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/weather/thundering.ogg does not exist, cannot add it to event minecraft:weather.rain
227 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/weather/thunder7.ogg does not exist, cannot add it to event minecraft:entity.lightning_bolt.thunder
228 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/weather/thunder8.ogg does not exist, cannot add it to event minecraft:entity.lightning_bolt.thunder
229 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/wind/snowwind1.ogg does not exist, cannot add it to event minecraft:entity.polar_bear.ambient
230 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/wind/snowwind2.ogg does not exist, cannot add it to event minecraft:entity.polar_bear.ambient
231 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/forest.ogg does not exist, cannot add it to event minecraft:entity.fox.ambient
232 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/bridwind3.ogg does not exist, cannot add it to event minecraft:entity.sniffer.idle
233 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/wind/windleave.ogg does not exist, cannot add it to event minecraft:block.vine.step
234 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/birdlong1.ogg does not exist, cannot add it to event minecraft:block.vine.step
235 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/jungle8.ogg does not exist, cannot add it to event minecraft:block.vine.step
236 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/birdlong2.ogg does not exist, cannot add it to event minecraft:entity.panda.step
237 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/jungle7.ogg does not exist, cannot add it to event minecraft:entity.parrot.fly
238 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/birdlong3.ogg does not exist, cannot add it to event minecraft:entity.parrot.fly
239 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/chirping8.ogg does not exist, cannot add it to event minecraft:entity.parrot.ambient
240 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/longrbird2.ogg does not exist, cannot add it to event minecraft:entity.bee.loop
241 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/windleaves.ogg does not exist, cannot add it to event minecraft:block.grass.step
242 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/forest.ogg does not exist, cannot add it to event minecraft:block.gravel.step
243 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/night2.ogg does not exist, cannot add it to event minecraft:block.gravel.step
244 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/unknown/wendigo.ogg does not exist, cannot add it to event minecraft:block.gravel.step
245 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/wind/sandwind1.ogg does not exist, cannot add it to event minecraft:block.sand.step
246 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/snowstorm.ogg does not exist, cannot add it to event minecraft:block.snow.step
247 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/chiping1.ogg does not exist, cannot add it to event minecraft:block.snow.step
248 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/pery/hawk.ogg does not exist, cannot add it to event minecraft:block.snow.step
249 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/lightwind.ogg does not exist, cannot add it to event minecraft:block.snow.step
250 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/unknown/wendigo.ogg does not exist, cannot add it to event minecraft:block.snow.step
251 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/unknown/wendogo2.ogg does not exist, cannot add it to event minecraft:block.snow.step
252 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/swamp.ogg does not exist, cannot add it to event minecraft:block.mud.step
253 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/swamp2.ogg does not exist, cannot add it to event minecraft:block.mud.step
254 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/night3.ogg does not exist, cannot add it to event minecraft:block.mud.step
255 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/jungle7.ogg does not exist, cannot add it to event minecraft:block.mud.step
256 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/ambience/frogshort2.ogg does not exist, cannot add it to event minecraft:block.mud.step
257 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/underground/cave-water6.ogg does not exist, cannot add it to event minecraft:block.amethyst_block.step
258 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through9.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
259 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through9.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
260 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through8.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
261 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through9.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
262 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through10.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
263 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through11.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
264 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through9.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
265 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through8.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
266 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through9.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
267 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through10.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
268 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/blocks/step/petals/leaves_through11.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step
269 | [12:33:06] [Worker-Main-10/WARN]: File minecraft:sounds/Remastered/ambient/bird/longbird6.ogg does not exist, cannot add it to event minecraft:block.pink_petals.step

**Comment by OreCruncher** [comment]
Those sounds are not from Dynamic Surroundings. Because "remastered" is in the name it could be from a version that was created by another person.

**Comment by OreCruncher** [comment]
Closing issue as it is not related to my code.
