### ISSUE TITLE
1.18 ?

### ISSUE THREAD

**Issue by Chuunkyz** [OreCruncher/DynamicSurroundingsFabric#13]
hey, i'm waiting that now :)

**Comment by SpiffyJUNIOR** [comment]
1.18 just released a few days ago, give the author some time

**Comment by CrazyGoGo42** [comment]
This is nothing official. You might encounter some bugs. I am using it myself. No bugs so far. 
https://www.mediafire.com/file/pgujklhhhltyokc/DynamicSurroundings-Fabric-1.18-0.0.4.jar/file

**Comment by Catboi8** [comment]
> This is nothing official. You might encounter some bugs. I am using it myself. No bugs so far.
> Link is up for 2 weeks:
> https://www.mediafire.com/file/pgujklhhhltyokc/DynamicSurroundings-Fabric-1.18-0.0.4.jar/file

for those wondering but lazy, according to [virus total](https://www.virustotal.com/gui/url/4491deec473a2699d7c71d8143fe307f5716968f904b1b070c6ce3f332e774a9?nocache=1) it doesn't seem to be a virus but I would still use at your own risk

**Comment by keatit71** [comment]
> This is nothing official. You might encounter some bugs. I am using it myself. No bugs so far. Link is up for 2 weeks: [mediafire.com/file/pgujklhhhltyokc/DynamicSurroundings-Fabric-1.18-0.0.4.jar/file](https://www.mediafire.com/file/pgujklhhhltyokc/DynamicSurroundings-Fabric-1.18-0.0.4.jar/file)

that version doesn't work with 1.18.1

**Comment by spnda** [comment]
> > This is nothing official. You might encounter some bugs. I am using it myself. No bugs so far. Link is up for 2 weeks: [mediafire.com/file/pgujklhhhltyokc/DynamicSurroundings-Fabric-1.18-0.0.4.jar/file](https://www.mediafire.com/file/pgujklhhhltyokc/DynamicSurroundings-Fabric-1.18-0.0.4.jar/file)
> 
> that version doesn't work with 1.18.1

If you can compile it yourself you can check my PR at https://github.com/OreCruncher/DynamicSurroundingsFabric/pull/14. It's updated to work on 1.18 and 1.18.1 and in my experience it has worked perfectly with no issues. If you want, I can provide you with a JAR file.

**Comment by keatit71** [comment]
Yeah if you could provide that would be good not gone so far as to compile GitHub yet for a mod

**Comment by spnda** [comment]
@keatit71 It might be the same binary as @CrazyGoGo42 posted, but I just freshly compiled it :)
[DynamicSurroundings-Fabric-1.18-0.0.4.zip](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/7706096/DynamicSurroundings-Fabric-1.18-0.0.4.zip)

**Comment by keatit71** [comment]
yeah that works fine but didn't the 1.17 version have a carpet config compatibility so i can change settings in game

**Comment by keatit71** [comment]
i'm sure you could in the 1.17 version

**Comment by CormacZ** [comment]
![image](https://user-images.githubusercontent.com/71203678/147260867-c198c91d-bfa3-476a-b000-df9f9b62c0c0.png)

**Comment by HarvelsX** [comment]
Here's another way to get this great mod on 1.18.1 here https://github.com/HarvelsX/DynamicSurroundingsFabric/actions/runs/1641972118
These are the latest commits with PR

**Comment by CormacZ** [comment]
> 

Can't wait for the 1.19 version out
