### ISSUE TITLE
Thunder volume

### ISSUE THREAD

**Issue by 5467864** [OreCruncher/DynamicSurroundingsFabric#134]
Adjusting the thunder volume has no effect, including the vanilla version

**Comment by OreCruncher** [comment]
Thunder is a weird thing in MC.  The vanilla volume is some ridiculous number like 12,000. The thunder sound is positional, but given how the sound is configured it can be heard quite some distance away. Which way are you trying to adjust the volume?

**Comment by 5467864** [comment]
![img](https://github.com/user-attachments/assets/b980eff5-6144-4dbd-967a-422cc4467989)

**Comment by OreCruncher** [comment]
So this would set it to 10,920, which will does not change the volume in single player.  Best it would do is reduce the distance in multiplayer, meaning your chance of hearing it when the bolt strikes around another player in the world is reduced. Even when set to 1% the volume will be 120.  Normally, volume is somewhere between 0.0 and 1.0 with a range of 16 blocks.

**Comment by 5467864** [comment]
OK, thanks for your explanation
