### ISSUE TITLE
Cannot invoke "org.orecruncher.dsurround.processing.misc.BlockEffectManager.tick

### ISSUE THREAD

**Issue by AlisterGontineac** [OreCruncher/DynamicSurroundingsFabric#15]
DynamicSurroundings-Fabric-1.17.1-0.0.4

Crashed after entering the nether

Minecraft 1.17.1
Fabric loader 0.12.8
Java Version: 16.0.2, Azul

[crash-2021-12-14_19.46.01-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/7715685/crash-2021-12-14_19.46.01-client.txt)

**Comment by OreCruncher** [comment]
Pushed 1.20.4 update to Modrinth and CurseForge (though Curse is going to take a bit to be available).
