### ISSUE TITLE
/playsound from command blocks does not work

### ISSUE THREAD

**Issue by prototype464** [OreCruncher/DynamicSurroundingsFabric#19]
I work on command block operated minigames and a big part of them is sound cues played by command blocks with the /playsound command, using this mod (latest version) prevents me from hearing /playsound and I've tried many things to see if I can find out what's causing it, boiled down to this mod. pls fix

Using the following mods:
Xaero's World Map
Xaero's BetterPvP
Dark Loading Screen
Dynamic FPS
Fabric API
FerriteCore
ModMenu
Notes
OptiFabric
OptiFine
Presence Footsteps
ReplayMod

**Comment by OreCruncher** [comment]
This is an oldie.  Curious as to what sound you were trying to play and whether this was on a server.
