### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by OverloadedWithMods** [OreCruncher/DynamicSurroundingsFabric#21]
Update to 1.18.2?
This mod is really good and was literally in most 1.12.2 packs. 
Also, 1.18 should be on curse forge, it will get numerous downloads.

**Comment by HarvelsX** [comment]
Try https://github.com/ThexXTURBOXx/DynamicSurroundingsFabric/suites/5553502758/artifacts/179155527

**Comment by MrGingerBreadd** [comment]
> Try https://github.com/ThexXTURBOXx/DynamicSurroundingsFabric/suites/5553502758/artifacts/179155527

this link is broken

**Comment by OverloadedWithMods** [comment]
> Try https://github.com/ThexXTURBOXx/DynamicSurroundingsFabric/suites/5553502758/artifacts/179155527

Tysm dude!

**Comment by matt-zb** [comment]
Link is dead. What did it lead to? Looking for a 1.18.2 version to use. Thanks!
