### ISSUE TITLE
Some things missing from the forge version

### ISSUE THREAD

**Issue by eburnham18** [OreCruncher/DynamicSurroundingsFabric#22]
One of the more notable things missing is the armor sounds when walking around as well as a couple visuals such as the auroras. They appear to be present in the forge version but are missing in the fabric version.

**Comment by OreCruncher** [comment]
Yes - these were intentionally dropped.  Info is called out on the CurseForge project page:  https://legacy.curseforge.com/minecraft/mc-mods/dynamic-surroundings-fabric-edition
