### ISSUE TITLE
Crash when it's raining (Optifabric/Optifine)

### ISSUE THREAD

**Issue by zuliwa** [OreCruncher/DynamicSurroundingsFabric#23]
Whenever it starts raining, or I load into my world while it's raining I get a "Saving World" message, and then the game closes.
This happens only with optifine/optifabric enabled.
I am using the latest build for 1.18.1 that I could find. I am using 1.18.1 because I intend to use this alongside other mods, some of which do not support 1.18.2

The launcher gives me this error code:
> The game crashed whilst exception while adding particle
>Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_703.method_3084(float, float, float)" because "fx" is null
>Exit Code: -1

Full crash log:
[crash-2022-04-30_14.42.50-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/8596914/crash-2022-04-30_14.42.50-client.txt)

**Comment by OreCruncher** [comment]
Looks to be a 1.18x related release?
