### ISSUE TITLE
Properly escaping unicode in fabric.mod.json

### ISSUE THREAD

**Issue by PerikiyoXD** [OreCruncher/DynamicSurroundingsFabric#24]
Project `fabric.mod.json`
```json
{
  "schemaVersion": 1,
  "id": "dsurround",
  "version": "${version}",
  "name": "\u00a76Dynamic Surroundings\u00a7r: \u00a7eFabric Edition",
...
```

Output `fabric.mod.json` (jar)
```json
{
  "schemaVersion": 1,
  "id": "dsurround",
  "version": "0.0.4",
  "name": "Â§6Dynamic SurroundingsÂ§r: Â§eFabric Edition",
...
```

As you can see, `name` escapes `\u00a76` into `Â§` when resources are processed.

To fix the issue:

`build.gradle`:
```diff
     filesMatching("fabric.mod.json") {
-        expand "version": project.version
+        expand (version: project.version) {
+            escapeBackslash = true
+        }
     }
```

**Comment by PerikiyoXD** [comment]
This work has been done over fork/branch for 1.18.2. Extrapolates to this repo as well.

**Comment by OreCruncher** [comment]
Fixing up various json files to use the unicode escape.  Will show up in the 1.20.4 update.

**Comment by OreCruncher** [comment]
Pushed 1.20.4 update to Modrinth and CurseForge (though Curse is going to take a bit to be available).
