### ISSUE TITLE
Underwater sounds getting louder

### ISSUE THREAD

**Issue by bungee-boy** [OreCruncher/DynamicSurroundingsFabric#26]
Hi, this mod is really good - I was just wondering if anybody knows about this weird bug or if its just me. 
Basically when I go underwater the ambient sounds do not get muffled like normal and instead become progressively louder and more distorted the longer I stay underwater, and once out of the water the ambient sounds return to normal volume. I can give logs and stuff if anyone needs them. I have only tested this in the Jungle and Bamboo Jungle Biome for now since I was just playing casually with same results in both.

This may just be a conflict because I do have other mods but is still kinda strange....

**Comment by Tenuuu** [comment]
Having similar situation here as well. What mods are you using?

**Comment by bungee-boy** [comment]
Hey, here are my current mods and I also use Sildur's vibrant shaders v1.32
(Extreme) and some resource packs, however they do not affect the glitch.
Hope this helps!

**Comment by OreCruncher** [comment]
What an oversight on my part.  Pulling in the fix for the 1.20.4 update.

**Comment by OreCruncher** [comment]
Pushed 1.20.4 update to Modrinth and CurseForge (though Curse is going to take a bit to be available).
