### ISSUE TITLE
No footstep sound

### ISSUE THREAD

**Issue by FazbearFan426** [OreCruncher/DynamicSurroundingsFabric#3]
I can't hear any footstep sounds in this mod.

**Comment by OreCruncher** [comment]
That feature is not in the mod.  If I do bring it forward it will more than likely change.

**Comment by OreCruncher** [comment]
Check this out: https://modrinth.com/mod/presence-footsteps.  DS uses a heavily modified version of PF so this may do the trick for you in terms of footsteps.
