### ISSUE TITLE
Support for MC 1.20.4

### ISSUE THREAD

**Issue by HyTap** [OreCruncher/DynamicSurroundingsFabric#32]
Any plans for 1.20?
I saw the user [jmattingley23](https://github.com/jmattingley23) working on a 1.19 version a couple of years ago but no news from the original programmer.

**Comment by MotMomet** [comment]
I'm looking for 1.20 version. Please make it happen. lol
Also if anyone know how to port mods to newer versions simply? like i dont have much knowledge about it and i want to play this mod in 1.20

**Comment by OreCruncher** [comment]
Pushed 1.20.4 update to Modrinth and CurseForge (though Curse is going to take a bit to be available).
