### ISSUE TITLE
[1.20.1] Fabric backport of 1.20.4

### ISSUE THREAD

**Issue by Rebel459** [OreCruncher/DynamicSurroundingsFabric#35]
Just wanted to start this off with saying thanks for the 1.20 update, this mod’s absolutely incredible.
And yes, I know this has only just released for 1.20.4, but it would be absolutely incredible if a 1.20.1 release was possible in the future, as this awesome mod would massively improve so many modpacks, with which all the large ones are forced to use 1.20.1 due to mod availability. 
Thanks for your time

**Comment by OreCruncher** [comment]
I am not sure what it would take to get a 1.20.1 version.  It was a real pain getting it to 1.20.4.  I will to my list when I get a chance - no promises. :)

**Comment by OreCruncher** [comment]
For what it's worth - the mod seems to run with Minecraft 1.20.3, though the in game sound config menu has some jank.  1.20.2 and earlier would require code changes.

**Comment by Rebel459** [comment]
Really appreciate the response and glad to hear you’re happy to consider it! Hopefully it’s not too big a task, but no issue if you don’t end up doing it. Have a good day, and thanks for supporting and developing such a great mod! :)

**Comment by sternschnaube** [comment]
Would love to use the mod on 1.20.2 😊

**Comment by Thefatsparrow** [comment]
any updates on the backport?

**Comment by OreCruncher** [comment]
I haven't finished with 1.20.4 ;)  I am almost done, though.  Once that is completed I will be looking at Forge/Neoforge.  Once THAT is done I can evaluate backports.

**Comment by Thefatsparrow** [comment]
cool keep us updated!

**Comment by Wanderer70** [comment]
Actually, since we have Sinytra Connector, focusing on a backport to 1.20.1 would be a more preferable option.

**Comment by OreCruncher** [comment]
Not sure if I want to be in a position to support something like Sinytra connector.  Though, technically, there shouldn't be anything for me to do I don't want to field support issues involving components like that. I did enough looking at Forge recently and the startup behaviors are different enough to give my mod headaches, and I do not think something like Sinytra would improve things.

This being said, the work I am doing for the next release will simplify any porting I may do, whether to Forge or even earlier versions of Fabric.  I did a trial of doing a Fabric 1.20.1 build and it looks pretty reasonable. Once I push the release I am working on I will take a harder look at a Fabric 1.20.1 release.

**Comment by OreCruncher** [comment]
And I have a 1.20.1 version running.  The sound config GUI needs some TLC and I have to do a bunch more testing.  Looks promising.

**Comment by Rebel459** [comment]
I’m super hyped to see it!
Do you want some help testing?

**Comment by OreCruncher** [comment]
Unfortunately, some of the stuff I am looking for is based on my internal understanding of the mod. The weird corner cases that keep me up at night. :)

Any recommendations for a 1.20.1 modpack?  Just ran through Fabulously Optimized.  Looking for something that stresses the environment with different things.

**Comment by Rebel459** [comment]
You want to stress it? Honestly use mine lmao (Legacies on modrinth), I am planning to use DynamicSurroundings after all
I have way too much cursed random niche crap in it, it’s a big (mod-count-wise) pack with over 250 mods
That or you could just use the regular old BetterMC etc

**Comment by Thefatsparrow** [comment]
Install terralith and continents that really stresses and tests your computer

**Comment by Rebel459** [comment]
…that’s not remotely what they meant by that

**Comment by OreCruncher** [comment]
@Rebel459 As an FYI - some of the biomes added by the pack do not have biome tags set so Dynamic Surroundings will not play biome effects in those areas. A datapack can supply the missing tags. When integrating DS into your pack you can do a "/dsdump biomes" to get a list of what DS thinks of the various biomes.

**Comment by OreCruncher** [comment]
Just pushed the 1.20.1 version to both CurseForge and Modrinth.

**Comment by Rebel459** [comment]
Thanks a ton for the heads-up, will do! And thanks so much for the port _and_ the backport, super excited to finally see you and Dynamic Surroundings return!

**Comment by OreCruncher** [comment]
For what it's worth it seems the 1.20.1 works with the Sinytra mod framework.  At least it loaded, I got biome sounds, debug screen, and I get cave reverb.

**Comment by sternschnaube** [comment]
Is 1.20.2 off the table? 👀

**Comment by OreCruncher** [comment]
Not sure how many people are on 1.20.2.  There are differences between 1.20.1 and .2 that Mojang made that would cause me to have a special build.

**Comment by sternschnaube** [comment]
If it's not that much work it would be cool, otherwise it's already great that you supported 1.201 😊
