### ISSUE TITLE
[1.20.4] Incompatible with Sound Physics Remastered

### ISSUE THREAD

**Issue by rght925h** [OreCruncher/DynamicSurroundingsFabric#39]
I realise both mods largely do the same, but Sound Physics Remastered (https://github.com/henkelmax/sound-physics-remastered) is incompatible with the current version of DynamicSurroundingsFabric. I use Sound Physics Remastered for its Simple Voice Chat (https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat) support. Dynamic Surroundings Fabric, however, also adds brilliant biome and environmental sounds. I used to use both, with DSF's sound physics disabled. 

When using both, Minecraft won't launch:

`[Render thread/WARN]: @Redirect conflict. Skipping sound_physics_remastered.mixins.json:LibraryMixin from mod sound_physics_remastered->@Redirect::requestAuxSends(JLjava/nio/IntBuffer;)J with priority 1000, already redirected by dsurround.mixins.json:audio.MixinSoundEngine from mod dsurround->@Redirect::dsurround_buildCapabilities(JLjava/nio/IntBuffer;)J with priority 1000`

Would there be a potential fix or workaround? My apologies if this isn't desired or pertinent.

Thanks for this fantastic mod! :-)

**Comment by OreCruncher** [comment]
Good question - I will have to look into it.  In general, my philosophy is that if there is another specialty mod install that does these types of things I want to auto-disable my mod function.

**Comment by OreCruncher** [comment]
Yay for mixin extensions!  I reworked things a bit so that my enhanced sound processing is disabled in favor of SoundPhysics.  Question - is there a way to reduce the amount of reverb in SoundPhysics?  It has a little bit too much and borders on echo for my taste.

**Comment by rght925h** [comment]
Haha, wow, that was quick! Thank you very much, man!

Indeed, Sound Physics Remastered gives the user full control over reverb. 
I hope this isn't too detailed, but here are the primary parameters to fine-tune the reverberation profile:

```
attenuation_factor=1.0
reverb_gain=1.0
reverb_brightness=1.0
block_absorption=1.0
occlusion_variation=0.35
default_block_reflectivity=0.5
default_block_occlusion_factor=1.0
sound_distance_allowance=4.0
air_absorption=1.0
```

If the echo is perceived as too strong, I'd suggest dialling in attenuation, gain, and reflectivity first. It can be adjusted to sound very similar to how DynamicSurroundingsFabric sounds. My main interest in using Sound Physics Remastered (customisations aside), is its voice support. It's bloody brilliant hearing other players' voices, as well as your own, echo through caves. :-) 

Anyway, thank you so much for addressing this!

**Comment by OreCruncher** [comment]
Pushed 1.20.4-0.0.8
