### ISSUE TITLE
We Need This For 1.19.4

### ISSUE THREAD

**Issue by ghost** [OreCruncher/DynamicSurroundingsFabric#49]
**Hay Dynamic Surroundings Developer's Please Add 1.19.4**

**Comment by Tapacywka** [comment]
For now, you can use an unofficial fork that supports version 1.19.4 of the game.
At least until the developer of the original mod decides to make it for this version.
https://github.com/maksim789456/DynamicSurroundingsFabric

**Comment by Rebel459** [comment]
Yeah, i’d use the fork for now - 1.19.4 isn’t very well supported now and wasn’t even when it was the latest version

**Comment by OreCruncher** [comment]
Closing - no plans for 1.19.x support.
