### ISSUE TITLE
[1.20.x] Minimal particle settings cause mod to crash when around waterfalls

### ISSUE THREAD

**Issue by Jafoolery** [OreCruncher/DynamicSurroundingsFabric#58]
I recently installed dynamic surroundings into my mods folder and it crashes afew seconds into the world. Here is the log file.

[latest.log](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14017556/latest.log)

**Comment by OreCruncher** [comment]
What is your particle render level set to in the game options?

**Comment by Jafoolery** [comment]
Minimal

**Comment by OreCruncher** [comment]
It's what I suspected.  Two things you can do right now: increase from minimal to decreased, or disable the waterfall effect. I know what the issue is. I am in the midst of making other changes and will be uploading another build toward the weekend.

**Comment by OreCruncher** [comment]
Pushed update to CurseForge and Modrinth.
