### ISSUE TITLE
[1.20.x] Compatibility with Serene Season

### ISSUE THREAD

**Issue by OreCruncher** [OreCruncher/DynamicSurroundingsFabric#64]
Take into account seasonal temperature variations which can affect behaviors of the mod, such as frost breath and playing of certain biome sounds.

**Comment by Thefatsparrow** [comment]
could this be added to fabric seasons?

**Comment by OreCruncher** [comment]
They don't have a declared API set.  I would need something more formal that would allow me to get temerature and precipitation for a biome at a given block position. Once they add that then I can provide support. I don't want to hack around it because then it becomes fragile.

**Comment by OreCruncher** [comment]
Tested with the Legacy pack (which has Fabric Seasons) and it looks like the temperature that DS is using is affected by their seasons. With the next update it should work as it.

**Comment by Thefatsparrow** [comment]
What sound are added or changed in different seasons?

**Comment by OreCruncher** [comment]
It varies. In my rule set for various effects there is a check for whether water can freeze. Of course, this is based on temperature. In terms of the easiest to experience right away is the frost breath effect. Another easy one to spot is the firefly effect - they will not show if it's too cold.

**Comment by Thefatsparrow** [comment]
That is… amazing I’m replacing my ambient sounds mod with this one unless there compatible? Which is probably very unlikely

**Comment by OreCruncher** [comment]
Some players use both though there is overlap with what the mods are trying to achieve. I don't run with both because it's too much sound load for me. Give it a try.

**Comment by OreCruncher** [comment]
Pushed update to CurseForge and Modrinth.
