### ISSUE TITLE
[1.20.x] Incompatible with Quilted Fabric API due to missing registry.

### ISSUE THREAD

**Issue by Arrowpuppet** [OreCruncher/DynamicSurroundingsFabric#70]
_Posting this here as well as on [Quilt](https://github.com/QuiltMC/quilted-fabric-api/issues/147) just in case. Not entirely sure if this is applicable here, but I thought it'd be worth a shot._

This mod causes Quilt to crash on startup due to missing the "ResourceKey[minecraft:root / minecraft:worldgen/biome]" registry, thus being incompatible.

Would it be possible/feasible to resolve this on Dynamic Surroundings' side?

**Comment by OreCruncher** [comment]
I haven't tested with Quilt and do not claim compatibility. This being said, I would find this strange in that these are Vanilla things and not tied to a particular launcher or mod environment. I will hold open for now in case something develops.

**Comment by Arrowpuppet** [comment]
I understand. Just thought I might mention it here juuust in case it could be more practical to solve it with the mod itself! :)

**Comment by Arrowpuppet** [comment]
Actually it appears that this issue could be caused by QFAPI replacing the `FabricClientCommandSource` in FAPI with `QuiltClientCommandSource`, but I'm not sure why it's not just calling the same interface, as QFAPI also extends `FabricClientCommandSource` to `QuiltClientCommandSource`. (forgive me if I'm not understanding/wording this correctly, kind of a noob when it comes to coding)

**Comment by Arrowpuppet** [comment]
Welp, for now I am able to get minecraft to at least launch by removing `BiomeCommand.java` and removing line 13 from `Commands.java` in org.orecruncher.dsurround.fabric.commands, but obviously that means that functionality is now gone for me. At least that means it's definitely something related to `BiomeCommand.java`.

**Comment by OreCruncher** [comment]
I was curious about removing the commands.  I  was thinking of adding a config option to disable command registration, but wasn't sure of further downstream impacts of running under Quilt.  Let me know what you find.

**Comment by OreCruncher** [comment]
Posted 0.3.1 versions to CurseForge/GitHub. Added option to disable command registration.

**Comment by Arrowpuppet** [comment]
I'm kinda wondering if it might be better to disable the command registration by default so that it's compatible with quilt on first install, or if not perhaps add a note on the mod page that it needs to be disabled manually for quilt users.

**Comment by OreCruncher** [comment]
Actually what I want to do is auto disable if running under quilt. Just havn't spent time trying to figure out how to detect when running in a quilt environment.
