### ISSUE TITLE
[1.20.x] Document configuration process for external resource packs

### ISSUE THREAD

**Issue by TheInfinityUser** [OreCruncher/DynamicSurroundingsFabric#74]
https://dynamicsurroundings.readthedocs.io/en/master/
I was following this wiki to add mod compatibility for epic fight and some other weapon mods. I was running the mod on forge using Synitra Connector and I ran across a lot of issues.
1. The first issue was when I noticed that there was no dsurround.cfg file in the configs/dsurround/ directory. So I downloaded the file from this repository and added it to the directory. I added support for a few items and I also added the iceandfire.json file. I followed the steps in the docs. After I loaded up the game, I saw that no sounds played for the ice and fire weapons.
2. This brought me to the second issue. I checked the jar file and saw that there were no compatibility json files (which I previously didn't realise that they already existed internally).

Well, this brings me to the obvious question. How do you add mod compatibility for this mod as of now?

**Comment by OreCruncher** [comment]
Those docs for the 1.12.x forge versions.  Fabric version is a different animal. I haven't documented anything yet for Fabric as it is still WIP.

**Comment by OreCruncher** [comment]
https://dynamic-surroundings.readthedocs.io/en/latest/index.html
