### ISSUE TITLE
[Question] Is this compatible with the AmbientSounds mod ?

### ISSUE THREAD

**Issue by szunakabeats** [OreCruncher/DynamicSurroundingsFabric#75]
if i listen to the ambient sounds i think i can hear both ambient sounds playing

**Comment by OreCruncher** [comment]
They will both run supplying sounds.

**Comment by szunakabeats** [comment]
Okay, so I can just turn off the ambient sounds from dynamic surroundings ?

**Comment by OreCruncher** [comment]
Depends on what you want.  If you want ambient sounds, but do not want the ambient sounds of DS, then why install DS? The players I know of that use both want both.

**Comment by zndrmn** [comment]
I am one of those rare users who uses both, the more ambient sounds the better

**Comment by OreCruncher** [comment]
Closing as answered. If you have further questions just ask.
