### ISSUE TITLE
[1.20.x] Biome sounds not working when connecting to Paper server

### ISSUE THREAD

**Issue by DJHardLogic** [OreCruncher/DynamicSurroundingsFabric#76]
The biome sounds (such as ocean waves, birds chirping, crickets at night, etc.) don't work when I'm on a server, but other sounds like the wind at high altitudes and crows cawing do work. All the sounds work properly on singleplayer worlds.

**Comment by OreCruncher** [comment]
Modpack, server type, etc.  Also do you have ModernFix installed?

**Comment by DJHardLogic** [comment]
1.20.4-0.3.1
No I don't have ModernFix. Should I install that?

**Comment by DJHardLogic** [comment]
I have added ModernFix and it's just the same as before

**Comment by OreCruncher** [comment]
No - there was a bug in ModernFix that was recently fixed that could have affected scanning of resources.  What server are you connecting to? Vanilla, Fabric, etc? Also what modpack?  In my environment I can connect to a vanilla server hosted on LAN without problems.

**Comment by DJHardLogic** [comment]
![2024-02-04_13 47 13](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/158804650/bb829278-e237-4549-ad47-61a8d85e8e7a)
![2024-02-04_13 48 07](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/158804650/7a4af1e8-2300-4acf-9b7f-2fe7896a3b77)
I'm not sure what you mean by modpack, but I play on a mostly vanilla "paper" server. We have some plugins, but they're all just anti-cheat/anti-theft

**Comment by OreCruncher** [comment]
Hmm...paper.  What Fabric loader and API version? I have a suspicion.

**Comment by DJHardLogic** [comment]
fabric-installer-1.0.0 and fabric-api-0.93.1+1.20.4

**Comment by OreCruncher** [comment]
Can you update Fabric API to the latest for 1.20.4? Should be 0.95.4+1.20.4. Reason is there were fixes for the API firing the tag load event when a client joins.  I suspect that is not happening based on the screenshot you provided.

**Comment by DJHardLogic** [comment]
![2024-02-04_14 50 07](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/158804650/bda26fc2-aea4-440d-9f3c-6040d2146438)
Updated, but no change

**Comment by DJHardLogic** [comment]
![2024-02-04_14 52 42](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/158804650/4cd79231-c45b-44fa-921e-7874a9827df9)
Here's another biome at a different time of day. Don't know if that provides any more help

**Comment by OreCruncher** [comment]
I'm going to have to dig into this. For whatever reason the biome information I have cached during client connect is not matching the reality of the game play. My mod uses biome tags to determine which effects to play for a given biome. This biome tag analysis shows up as "Biome Traits" in the diagnostic overlay (roughly the 8th written line in the screen shot).

(I recall similar issues with Paper servers in the past - not sure as to the why's.)

**Comment by OreCruncher** [comment]
I have a fix. Need to do more testing.

**Comment by OreCruncher** [comment]
Pushed update to CurseForge and Modrinth.  CurseForge is dragging its feet per usual.
