### ISSUE TITLE
Sword equipping and sword use sound not working. 

### ISSUE THREAD

**Issue by xEyelessAngelx** [OreCruncher/DynamicSurroundingsFabric#81]
I can’t seem to figure out the issue. I have tried F3+T, I’ ve  restarted the game several times, re installed the  mods. Even went was far as delete the game and %appdata% and I still dont get the sound
I noticed I don’t even get it in vanilla. I can hear the armor clank, but can’t hear the equipping of the sword and the use of it. 
using version 1.20.1

**Comment by OreCruncher** [comment]
Is it enabled?  It is off by default.

**Comment by xEyelessAngelx** [comment]
I fixed it. I didn't realize i needed addition files to use the config. It was late and was super tired. Thanks for the tip though!

**Comment by OreCruncher** [comment]
No worries.  In prior versions of the mod it was enabled by default. Turns out a lot of players didn't like and wanted to turn off. This time I turned off as a default. :)
