### ISSUE TITLE
Crash on 1.20.1 0.3.2

### ISSUE THREAD

**Issue by Dalethium** [OreCruncher/DynamicSurroundingsFabric#82]
[crash-2024-02-09_12.33.56-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14224702/crash-2024-02-09_12.33.56-client.txt)

This error was not present on 0.3.1, If you need more info please let me know!

**Comment by Dalethium** [comment]
I stand corrected, this issue is the result of a change to my modpack and is still present on 0.3.1, 
[mod1s.zip](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14224806/mod1s.zip)
These are the changed mods that I updated/added between this working and not working. Let me know if you need more help!

**Comment by Dalethium** [comment]
Downgrading sodium, indium, and related mods fixed this. Seems to be a compat issue with the latest sodium.

**Comment by OreCruncher** [comment]
Would you happen to have the log?

**Comment by Dalethium** [comment]
Unfortunately not, it does not seem to be in my log folder, however, I noticed one other change I didn't mark down here : https://modrinth.com/mod/phantom-loader this library was removed from my pack while downgrading sodium.

**Comment by OreCruncher** [comment]
Interesting. I was looking at my code and it is possible to get a null ref if the client connection process does things out of sequence. I suspect this is what is happening.
