### ISSUE TITLE
Cracker's Wither Storm Mod Broken Music

### ISSUE THREAD

**Issue by Billnotic** [OreCruncher/DynamicSurroundingsFabric#84]
The most recent versions of this mod (past 0.2.2) break the music in Cracker's Wither Storm Mod.

**Comment by OreCruncher** [comment]
Their mod is not open source so I cannot go look at the code.  How is it broken?

**Comment by Billnotic** [comment]
Sorry for not responding sooner, I already disabled sound pruning and it fixed it. Strange but at least things are working now. The effect that muffles audio behind blocks also seems to affect the music from this mod, and the authors recommend disabling that. Is it because the music is auto labelled as ambient instead of music? Is there a way to fix it from your end or is it entirely up to them?

**Comment by OreCruncher** [comment]
Yes - their music is submitted as "normal" sounds - AMBIENT, HOSTILE, etc. If it is indeed MUSIC they should consider using the sound source/category of music. My mod specifically ignores music category as well as non-attenuated sounds.  (All the sliders in the sound option screen are considered sound source/categories.)
