### ISSUE TITLE
crash problem

### ISSUE THREAD

**Issue by BloopyDooby** [OreCruncher/DynamicSurroundingsFabric#86]
using an 1.19.3 version cuz they aint a 1.19 one, im tryna intall the 1.17 ver cuz no work with 1.20, and whenever i put the dynamic surroudings mod along with the presence footsteps mod, it crashes and i have to delete the two just to work;-;

**Comment by OreCruncher** [comment]
You need to contact the person who forked/published the 1.19.3 version.  I did not publish it.

**Comment by OreCruncher** [comment]
Closing.
