### ISSUE TITLE
[1.20.x] Crash due to concurrent access of randomizer

### ISSUE THREAD

**Issue by FaeWulf** [OreCruncher/DynamicSurroundingsFabric#87]
[crash-2024-02-13_13.41.17-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14257137/crash-2024-02-13_13.41.17-client.txt)

Version 1.20,4 - 0.3.2

**Comment by OreCruncher** [comment]
What modpack, and how often does it occur?

**Comment by FaeWulf** [comment]
> What modpack, and how often does it occur?

Lastest fabulously optimized.
I don't know what triggering it, not very often, it is very random (sometimes crashed while walking on ice berg, sometimes crashed while building base...)

**Comment by OreCruncher** [comment]
My mod is a client side mod, meaning my logic executes on the render thread (well, mostly). This crash is telling me that there is another thread that is trying to use a randomizer instance that I created for the render thread, which is something that should not be occurring. I would imagine this issue would be infrequent and occur randomly just as you are experiencing.

**Comment by OreCruncher** [comment]
Pushed update 0.3.3 to CurseForge and Modrinth.
