### ISSUE TITLE
When server is closed, the client crashes

### ISSUE THREAD

**Issue by Fishvap** [OreCruncher/DynamicSurroundingsFabric#9]
[crash-2021-10-29_21.47.00-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/7445009/crash-2021-10-29_21.47.00-client.txt)
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 29/10/2021, 21:47
Description: Unexpected error

java.lang.NullPointerException: Cannot invoke "org.orecruncher.dsurround.processing.misc.BlockEffectManager.tick(net.minecraft.class_1657)" because "this.blockEffects" is null
	at org.orecruncher.dsurround.processing.AreaBlockEffects.process(AreaBlockEffects.java:32)
	at org.orecruncher.dsurround.processing.Handlers.onTick(Handlers.java:109)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zii000$onEndTick(class_310.java:5573)
	at net.minecraft.class_310.method_1574(class_310.java:1806)
	at net.minecraft.class_310.method_1523(class_310.java:1081)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.orecruncher.dsurround.processing.AreaBlockEffects.process(AreaBlockEffects.java:32)
	at org.orecruncher.dsurround.processing.Handlers.onTick(Handlers.java:109)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.class_310.handler$zii000$onEndTick(class_310.java:5573)

-- Affected level --
Details:
	All players: 1 total; [class_746['Fishvap'/143, l='ClientLevel', x=-1371.13, y=70.00, z=857.44]]
	Chunk stats: 1024, 306
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,65,-221), Section: (at 0,1,3 in 7,4,-14; chunk contains blocks 112,0,-224 to 127,255,-209), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1644258 game time, 2269078 day time
	Server brand: fabric
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:370)
	at net.minecraft.class_310.method_1587(class_310.java:2399)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:568)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.1, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), AdoptOpenJDK
	Memory: 1546327504 bytes (1474 MiB) / 4294967296 bytes (4096 MiB) up to 6417285120 bytes (6120 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800H with Radeon Graphics         
	Identifier: AuthenticAMD Family 25 Model 80 Stepping 0
	Microarchitecture: Zen 3
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Laptop GPU
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2520
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7212
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x1638
	Graphics card #1 versionInfo: DriverVersion=27.20.14044.4001
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 35257.18
	Virtual memory used (MB): 31160.17
	Swap memory total (MB): 19464.87
	Swap memory used (MB): 2193.99
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx6120m
	Fabric Mods: 
		additionaladditions: Additional Additions 2.1.3
		adorn: Adorn 2.2.0+1.17.1
		animatica: Animatica 0.1+1.17
		antiqueatlas: Antique Atlas 6.1.0-fabric-mc1.17.1
		authme: Auth Me 1.5.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		axolotlitemfix: Axolotl Item Fix 1.1.2
		bettermounthud: Better Mount HUD 1.1.2
		betterpingdisplay: Better Ping Display 1.1
		cardinal-components-base: Cardinal Components API (base) 3.1.1
		cardinal-components-entity: Cardinal Components API (entities) 3.1.1
		chalk: Chalk 1.0.0
		chat_heads: Chat Heads 0.5.0
		citresewn: CITResewn 0.8.0
		cleardespawn: Clear Despawn 1.17.1-1.1.2
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v5 5.0.38
		coloredcampfire: Colorful Campfire Smoke 1.1.5-1.16
		com_electronwill_night-config_core: core 3.6.3
		com_electronwill_night-config_toml: toml 3.6.3
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		comforts: Comforts 0.0.7-1.17.1
		continuity: Continuity 1.0.1+1.17
		couplings: Couplings 1.5.0+1.17
		crowdin-translate: CrowdinTranslate 1.3+1.17
		deathlog: DeathLog 0.2.1
		dsurround: §6Dynamic Surroundings§r: §eFabric Edition 0.0.4
		dual_riders: DualRiders 1.0.5
		fabric: Fabric API 0.41.0+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446313
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+a02b446318
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.3.0+57bef5a318
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+cbda931818
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+36b77c3e18
		fabric-language-kotlin: Fabric Language Kotlin 1.6.5+kotlin.1.5.31
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-models-v0: Fabric Models (v0) 0.3.0+a02b446318
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.11+7931163218
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.4+cbda931818
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.8+cbda931818
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.4+7931163218
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.5+7931163218
		fabric-rendering-v1: Fabric Rendering (v1) 1.9.0+7931163218
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.4+cbda931818
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+a02b446318
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.4.0+7931163218
		fabricloader: Fabric Loader 0.12.2
		fabrilousupdater: FabrilousUpdater 2.4
		fabrishot: Fabrishot 1.5.1
		fallflyinglib: FallFlyingLib 3.0.0-beta.2
		fallingleaves: Falling Leaves 1.7.4+1.17.1
		fastfurnace: FastFurnace 1.17-3.0
		ferritecore: FerriteCore 3.0.3
		fiber: fiber 0.23.0-2
		figura: Figura 0.0.7-rc.2-patch.1
		gbfabrictools: GBfabrictools 1.3.4+1.17
		horsestatsvanilla: Horse Stats Vanilla 4.1.8
		indium: Indium 1.0.0+mc1.17.1
		interactic: Interactic 0.1.6-1.17
		itemmodelfix: Item Model Fix 1.0.2+1.17
		jankson: Jankson 3.0.1+j1.2.0
		java: OpenJDK 64-Bit Server VM 16
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		kibe: Kibe 1.9.3-BETA+1.17
		kirin: Kirin UI 1.9.1
		lambdynlights: LambDynamicLights 2.0.2+1.17
		lapisreserve: Lapis Reserve 1.0.8
		lazydfu: LazyDFU 0.1.2
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 4.1.3+1.17.1
		libninepatch: LibNinePatch 1.1.0
		libzoomer: LibZoomer 0.2.1+1.17
		lovely_snails: Lovely Snails 1.0.3+1.17
		mavm: More Axolotl Variants Mod 1.0.5
		maybe-data: Maybe data 1.0.1-1.17
		midnightlib: MidnightLib 0.2.6
		minecraft: Minecraft 1.17.1
		modmenu: Mod Menu 2.0.14
		monsters_in_the_closet: Monsters in the Closet 1.0.2+1.17
		nomoreglowingpots: No More Glowing Pots 1.0.2
		okzoomer: Ok Zoomer 5.0.0-beta.2+1.17
		omega-config: OmegaConfig 1.0.8
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.5.31
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.5.31
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.5.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.5.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.0
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.0
		org_luaj_luaj-jse: luaj-jse 3.0.1
		org_openjdk_nashorn_nashorn-core: nashorn-core 15.3
		pehkui: Pehkui 2.5.3+1.14.4-1.18
		perspectivemod: Perspective Mod Redux 0.0.5_01
		picturesign: PictureSign 1.1.0
		playerabilitylib: Pal 1.3.0
		presencefootsteps: Presence Footsteps r32-1.17-rc1
		repurposed_structures: Repurposed Structures 2.4.1+1.17.1
		reroll: Reroll 1.3.0-1.17.1
		seamless_loading_screen: Seamless Loading Screen 1.3.6+1.17.1
		sodium: Sodium 0.3.2+build.684
		somnus: Somnus API 0.0.13-1.17.1
		spruceui: SpruceUI 3.2.0+1.17
		starlight: Starlight 1.0.0+fabric.73f6d37
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		strawdummy: Straw Dummy 1.5.0
		talkbubbles: Talk Bubbles 1.0.0
		titlefixer: Title Fixer 1.0+1.17
		trade: Trade 1.2.1
		umollu_ash: ASH - Another Simple HUD 1.1.15
		voicechat: Simple Voice Chat 1.17.1-2.1.5
		winged: Winged Mod 1.17.1-3.0.0
		wolveswitharmor: Wolves With Armor 1.6.1-1.17.1
		xlpackets: XLPackets 2.0-1.17
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 3.2.0 NVIDIA 472.12, NVIDIA Corporation
	Window size: 4000x1600
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 5800H with Radeon Graphics

**Comment by HarvelsX** [comment]
Duplicate https://github.com/OreCruncher/DynamicSurroundingsFabric/issues/15, decided in https://github.com/OreCruncher/DynamicSurroundingsFabric/pull/17

**Comment by HarvelsX** [comment]
@Fishvap, plz close this issue

**Comment by Fishvap** [comment]
what? why? this is the original issue? it predates the others

**Comment by HarvelsX** [comment]
Oh, I'm sorry.

**Comment by showierdata9978** [comment]
https://crashy.net/82vl9sr9dXOAowBvWN34

**Comment by OreCruncher** [comment]
Pushed 1.20.4 update to Modrinth and CurseForge (though Curse is going to take a bit to be available).
