### ISSUE TITLE
Crash on Launching the game with Quilt Loader (idk if its support or not)

### ISSUE THREAD

**Issue by MotMomet** [OreCruncher/DynamicSurroundingsFabric#93]
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/141963182/03c92976-bca3-4e44-abe8-7ed131d21527)
[crash-2024-02-24_15.24.17-client.txt](https://github.com/OreCruncher/DynamicSurroundingsFabric/files/14392794/crash-2024-02-24_15.24.17-client.txt)
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/141963182/0574b5e6-8730-49f9-9a6d-8a23373faeaa)
only mods i have

**Comment by OreCruncher** [comment]
You try the latest version of dynamic surroundings? In general, I do not officially support quilt. However, I will fix simple bugs if it makes the mod work.

**Comment by MotMomet** [comment]
> You try the latest version of dynamic surroundings? In general, I do not officially support quilt. However, I will fix simple bugs if it makes the mod work.

it is 0.3.1
