### ISSUE TITLE
[1.20.x] Certain sounds from the mod "Spectrum" do not play with "Enhanced Sound Processing" enabled

### ISSUE THREAD

**Issue by unilock** [OreCruncher/DynamicSurroundingsFabric#94]
When Dynamic Surroundings' "Enhanced Sound Processing" is enabled, certain sounds from [Spectrum](https://modrinth.com/mod/spectrum) do not play - namely, the sounds that would normally play when crafting items using Spectrum's various means of doing so.

To reproduce:

1. Install Fabric Loader, Spectrum, and dependencies (*not* Dynamic Surroundings)
2. Start the game; create a new creative mode world
3. Give yourself a "Pigment Pedestal" (the one that says "Amethyst Variant" in the tooltip)
4. Give yourself several stacks of e.g. "Cyan Pigment"
5. Give yourself a "Paintbrush"
6. Place the Pigment Pedestal and fill every slot with at least several Cyan Pigment
7. Right-click the Pigment Pedestal with the Paintbrush
8. Note the music that plays while the Pigment Pedestal is crafting Cyan Blocks
9. Quit the game; install Dynamic Surroundings; restart the game, etc.
10. Try crafting the Cyan Blocks again
11. Note how the aforementioned music does not play

Disabling Dynamic Surroundings' "Enhanced Sound Processing" and restarting the game fixes this issue.

**Comment by OreCruncher** [comment]
Which version of Dynamic Surroundings?

**Comment by unilock** [comment]
> Which version of Dynamic Surroundings?

1.20.1-0.3.3.

> For some reason the play location is 0, 0, 0 unlike the completed crafting sound which is at the block location.

That would do it! Thanks for looking into it. I'll let the developer of Spectrum know.
