### ISSUE TITLE
No Sounds

### ISSUE THREAD

**Issue by Lukatony32** [OreCruncher/DynamicSurroundingsFabric#95]
I am Getting some sounds but for example swing switch and jump are missing i can play them over the menu

THe mods im using: 1.20.4 fabric 0.15.7
Blur
Bookshelf
Continuity
Creativecore
DS Fabric edition
Eating animation
Enchantment descriptions
ESSETIAL MOD
FAbric Api
Indium
Iris
item physic lite
mouse tweaks
Skin layers 3d
 Sodium Sodium Extra
Sound pHysics Remastered

**Comment by OreCruncher** [comment]
Did you enable toolbar/swing sounds in the config?  Also, jump sound was removed a while ago.

**Comment by Lukatony32** [comment]
Do i have to activity them first? 
Also i can play Jump in the menu and i really like it can i add it somehow?
