### ISSUE TITLE
1.20.2 Version?

### ISSUE THREAD

**Issue by SkeleBones** [OreCruncher/DynamicSurroundingsFabric#96]
Would it be possible to get a version for 1.20.2? If not, I understand completely.

**Comment by OreCruncher** [comment]
No plans.  Seems like the community is mostly on 1.20.1 or 1.20.4. I did look at 1.20.2 briefly and there are a good number of changes I would have to make to make it compatible. Keeping up with both 1.20.1 and 1.20.4 is taking up most of my modding time.

**Comment by SkeleBones** [comment]
Okay, that makes sense.
