### ISSUE TITLE
[1.20.x] Too Many Fireflies In Cherry Grove

### ISSUE THREAD

**Issue by SkeleBones** [OreCruncher/DynamicSurroundingsFabric#99]
I am on 1.20.4 and there seems to be a lot more fireflies than there are supposed to be when in a cherry grove biome. This was the best I could capture it, but it looks like a lot more when actually in game. 
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/38815328/b2e8200c-d4f6-402a-b842-4e0ff02529cf)
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/38815328/fa20ab1c-1804-4060-ab53-339e27d49bd6)
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/38815328/5fd097af-8134-469a-b559-9fcbc943aeb7)

**Comment by SkeleBones** [comment]
![image](https://github.com/OreCruncher/DynamicSurroundingsFabric/assets/38815328/5fd097af-8134-469a-b559-9fcbc943aeb7)

**Comment by SkeleBones** [comment]
I could be incorrect, but I think this is due to flowers causing the fireflies to display and because the cherry grove's floor is covered in flowers they end up being overwhelming.

**Comment by OreCruncher** [comment]
Firefly effect is tied to anything that is classified as a minecraft:flowers. BoP tags a lot of blocks to that tag.  It's just not the foliage on the ground - it'lso the leaf blocks in the trees. I could turn the frequency of spawning to a lower rate, but then it would reduce the rate of spawn across all biomes, including vanilla.  Basically a no win.

**Comment by OreCruncher** [comment]
No, but I can adjust the chance of spawn based on whether BoP is installed.  I was thinking cutting the frequency in half. Do you have any feel for how frequent it should be compared to what you have encountered?

**Comment by prototype464** [comment]
An option to configure the amount of fireflies from flowers (as well as their size and speed) I think would be a better compromise.

Something I liked about the older versions of this mod is the fireflies were smaller and slower, but in the current version they seem to zoom by and in this case for the Cherry Grove, I think, subjectively, it actually looks nice.

_ALL THE CONFIGS! >:D_

**Comment by SkeleBones** [comment]
I don't use BoP. So, this wouldn't help me. Since it can't be reduced based on the biome, the current way it is is fine.

**Comment by SkeleBones** [comment]
The issue in my screenshots are in a vanilla minecraft biome. I am confused why Biomes O' Plenty was brought up.
